export const SAVE_ALL_COUNTRIES = 'SAVE_ALL_COUNTRIES';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const SHOW_ALL = 'SHOW_ALL';
export const RESET_STATE = 'RESET_STATE';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const FILTER_COUNTRIES_BY_ACTIVITY = 'FILTER_COUNTRIES_BY_ACTIVITY';